### ISSUE TITLE
Xwayland window unmapped with `Ctrl` == on leaves it on

### ISSUE THREAD

**Issue by ildar** [pinnacle-comp/pinnacle#346]
### Describe the bug

as it is still pushed

### Reproduction steps

1. run `xterm`
2. push `Ctrl+d` in it. xterm window disappears
3. other Wayland windows act as Ctrl is still pushed, e.g.
4. in a Wayland terminal (e.g. Gnome-terminal) running mc arrow keys `Up` and `Down` don't work.

### Relevant parts of config

none

### Version info

pinnacle 0.1.0

Build Info:
    Build profile: release
    rustc version: 1.87.0
    Branch: VERGEN_IDEMPOTENT_OUTPUT
    Commit: 78a9eba

### Distro

ALTLinux p11

### GPU

i965

### Config language

Lua

**Comment by Ottatop** [comment]
I'm going to need more information as I can't reproduce this. Is the ctrl button stuck in all new Wayland windows you open? Is it stuck in other xwayland windows? If you have `wev` open in the Wayland terminal, does it receive the Ctrl when you `ctrl+d` xterm? And can you reproduce this with the default config?

**Comment by Ph4ntomas** [comment]
FYI, the bug you mentioned was fixed in smithay (https://github.com/Smithay/smithay/pull/1793)

**Comment by ildar** [comment]
built today's HEAD and still see it. Please reopen.

Can noone really reproduce it?

**Comment by ildar** [comment]
> Do you mean using with winit (nested mode inside another compositor/X Window Manager), or do you run pinnacle in a tty ?

Just run `pinnacle` in Pinnacle itself.

The above is just a note, no action required.

> Ok I'm going to need a screen capture

yep, I'll do that, @Ottatop !
